on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      matrix:
        board: [go60_lh, go60_rh]
    steps:
      - uses: actions/checkout@v4
      - name: West init
        run: west init -l config
      - name: West update
        run: west update
      - name: West zephyr-export
        run: west zephyr-export
      - name: West build
        run: west build -s zmk/app -d build -b ${{ matrix.board }} -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Upload firmware + elf
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.board }}-zmk
          path: |
            build/zephyr/zmk.uf2
            build/zephyr/zmk.elf